Signup_project/Signup_project/urls.py
from django.contrib import admin
from django.urls import path, include
# from myapp import views
from django.views.decorators.csrf import csrf_exempt


urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
]

Signup_project/myapp/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "myapp"

urlpatterns = [
    path('signup/', csrf_exempt(views.signupview),name='signup'),
    path('', csrf_exempt(views.Login),name='login'),
    path('signup/login',views.back_to_login ,name='back_to_login' ),
    path('next/next',views.Next,name='next'),
    path('next/profile',views.Profile,name='profile'),
    path('next/profile/',views.Profile,name='profile'),
    path('next/createchart',views.menu,name='menu'),
    path('next/menu',views.menu,name='menu'),
    #path('next/menu_list',views.menu_chart,name='menu_chart'),
   # path('next/uploadmenu',views.Uploadmenu,name='uploadmenu'),
    path('next/uploadmenu/', views.my_form, name='my_form'),
    path('next/logout', views.back_to_login, name='back_to_login'),
    path('next/uploadmenu/delete/<int:id>', views.delete, name='delete'),
    path('next/uploadmenu/delete2/<int:id>', views.delete2, name='delete2'),
    path('next/uploadmenu/delete3/<int:id>', views.delete3, name='delete3'),
    path('next/uploadmenu/delete4/<int:id>', views.delete4, name='delete4'),
    path('next/deletemenu/<int:id>', views.deletemenu, name='deletemenu'),
    path('next/post_it', views.post_it, name='post_it'),
    path('next/automatic', views.automatic, name='automatic'),
    
]

Signup_project/myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Normal(models.Model):
    fullname = models.CharField(max_length=200, blank=True, null=True, default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.fullname

class Gravy(models.Model):
    gravy = models.CharField(max_length=200, blank=True, null=True, default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.gravy

class Snacks(models.Model):
    snacks = models.CharField(max_length=200, blank=True, null=True, default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.snacks

class Sweets(models.Model):
    sweets = models.CharField(max_length=200, blank=True, null=True, default='')
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.sweets


class Breakfast(models.Model):
    breakfast = models.CharField(max_length=200)


class MyTable(models.Model):
    field1 = models.CharField(max_length=100)
    field2 = models.IntegerField()


class MenuName(models.Model):
    name_of_chart = models.CharField(max_length=200)

    def __str__(self):
        return self.name_of_chart
    
class Charts(models.Model):
    
    menuname = models.ForeignKey(MenuName, on_delete=models.CASCADE, null=True)
    DAY_CHOICES = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )
    MEAL_CHOICES = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
    )
    
    day = models.CharField(max_length=3, choices=DAY_CHOICES)
    meal = models.CharField(max_length=9, choices=MEAL_CHOICES)
    item = models.CharField(max_length=100, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.day} - {self.meal}: {self.item}"
    

class MenuItem(models.Model):
    
    DAY_CHOICES = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )
    MEAL_CHOICES = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
    )
    
    day = models.CharField(max_length=3, choices=DAY_CHOICES)
    meal = models.CharField(max_length=9, choices=MEAL_CHOICES)
    item = models.CharField(max_length=100, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.day} - {self.meal}: {self.item}"

class Post(models.Model):
    DAY_CHOICES = (
        ('mon', 'Monday'),
        ('tue', 'Tuesday'),
        ('wed', 'Wednesday'),
        ('thu', 'Thursday'),
        ('fri', 'Friday'),
        ('sat', 'Saturday'),
        ('sun', 'Sunday'),
    )
    MEAL_CHOICES = (
        ('breakfast', 'Breakfast'),
        ('lunch', 'Lunch'),
        ('dinner', 'Dinner'),
    )
    day = models.CharField(max_length=3, choices=DAY_CHOICES)
    meal = models.CharField(max_length=9, choices=MEAL_CHOICES)
    item = models.CharField(max_length=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.day} - {self.meal}: {self.item}"

    

Signup_project/myapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Normal, Gravy, Sweets, Snacks, Breakfast, MenuItem, Post, MenuName, Charts

class signupform(UserCreationForm):
    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email = forms.CharField(max_length=50)

    class meta:
        model = User
        fields=('username','password1','password2','email','first_name','last_name')

    def save(self,commit=True):
        user = super(signupform,self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

class GravyVeggie(forms.ModelForm):
  class Meta:
       model = Gravy
       fields = ["gravy",]
       labels = {'gravy': "ADD NEW DISH",}
       widgets = {'owner': forms.HiddenInput()}
       required = {
           "gravy":False,
       }

class SnacksMany(forms.ModelForm):
  class Meta:
       model = Snacks
       fields = ["snacks",]
       labels = {'snacks': "ADD NEW DISH",}
       widgets = {'owner': forms.HiddenInput()}
       required = {
           "snacks":False,
       }

class SweetsMany(forms.ModelForm):
  class Meta:
       model = Sweets
       fields = ["sweets",]
       labels = {'sweets': "ADD NEW DISH",}
       widgets = {'owner': forms.HiddenInput()}
       required = {
           "sweets":False,
       }

class NormalVeggie(forms.ModelForm):
  class Meta:
       model = Normal
       fields = ["fullname",]
       labels = {'fullname': "ADD NEW DISH",}
       widgets = {'owner': forms.HiddenInput()}
       required = {
           "fullname":False,
       }

class Morning(forms.ModelForm):
    class Meta:
      model = Breakfast
      fields = ["breakfast"]
      widgets = {'owner': forms.HiddenInput()}
      
class MenuItemForm(forms.ModelForm):
    class Meta:
        model = MenuItem
        fields = [ 'day', 'meal', 'item']
        widgets = {'owner': forms.HiddenInput()}


class CreateNewChart(forms.ModelForm):
    class Meta:
        model = MenuName
        fields = ['name_of_chart']
        widgets = {'owner': forms.HiddenInput()}

Signup_project/myapp/views.py
from django.shortcuts import render,redirect
from .forms import signupform
from .forms import NormalVeggie, GravyVeggie, SnacksMany, SweetsMany, MenuItemForm, CreateNewChart
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate
from django.contrib.auth import login
from .models import Normal, Gravy, Sweets, Snacks, MenuItem, Post, MenuName, Charts
from django.http import HttpResponse, HttpResponseRedirect, response
from django.urls import reverse_lazy
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import requests
from spoonacular import API
import json

@csrf_exempt

# Create your views here.

def signupview(request):
    if request.method=='POST':
        form = signupform(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:login')
        
    else:
        form = signupform()
    return render(request, 'signup.html',{'form':form})


def Login(request):
    if request.method=='POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request,user)
            return redirect('myapp:profile')

    return render(request, 'login.html')
    
def Next(request):
    return render(request, 'next.html')

def Profile(request):
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    meals = ['Breakfast', 'Lunch', 'Dinner']
    menu_chart = {}

    for day in days:
            menu_chart[day] = {}
            for meal in meals:
                menu_avialable = MenuItem.objects.filter(day=day[:3].lower(), meal=meal.lower(), owner=request.user)
                if menu_avialable:
                    menu_chart[day][meal] = menu_avialable[0].item
                else:
                    menu_chart[day][meal] = '-'
    return render(request, 'profile.html', {"menu_chart":menu_chart})

    

def Createchart(request):
    context={}
    context["dataset1"] = Normal.objects.all()
    context["dataset2"] = Gravy.objects.all()
    context["dataset3"] = Snacks.objects.all()
    context["dataset4"] = Sweets.objects.all()
    
    return render(request, 'createchart.html', context)

#def Uploadmenu(request):
    if request.method == "POST":
        form = CreateNewList(request.POST)

        if form.is_valid():
            n = form.cleaned_data["name"]
            t = Categories(name=n)
            t.save()

        
    else:
        form = CreateNewList()
    return render(request, 'uploadmenu.html', {"form":form})

#def index(request, id):
    ls = Categories.objects.get(id=id)
    
    if request.method == "POST":
        print(request.POST)
        if request.POST.get("save"):
            for item in ls.items_set.all:
                if request.POST.get("c" + str(item.id)) == "clicked":
                    item.complete = True
                else:
                    item.complete = False

                item.save()

        elif request.POST.get("newItem"):
            txt = request.POST.get("new")

            if len(txt) > 2:
                ls.item_set.create(text=txt, complete=False)
            else:
                print("invalid")

    return render(request, "list.html",{"ls":ls})

def my_form(request):
    context = {}
    form1 = NormalVeggie(request.POST or None)
    form2 = GravyVeggie(request.POST or None)
    form3 = SnacksMany(request.POST or None)
    form4 = SweetsMany(request.POST or None)
    if form1.is_valid() and form1.cleaned_data['fullname']:
        normall = form1.save(commit=False)
        normall.owner = request.user
        normall.save()
        
    
    context['form1']= form1
    context["dataset1"] = Normal.objects.filter(owner=request.user)

    if form2.is_valid() and form2.cleaned_data['gravy']:
        gravyy = form2.save(commit=False)
        gravyy.owner = request.user
        gravyy.save()
        
    
    context['form2']= form2
    context["dataset2"] = Gravy.objects.filter(owner=request.user)

    if form3.is_valid() and form3.cleaned_data['snacks']:
        snackss = form3.save(commit=False)
        snackss.owner = request.user
        snackss.save()
        
    
    context['form3']= form3
    context["dataset3"] = Snacks.objects.filter(owner=request.user)
    if form4.is_valid() and form4.cleaned_data['sweets']:
        sweetss = form4.save(commit=False)
        sweetss.owner = request.user
        sweetss.save()
        
    
    context['form4']= form4
    context["dataset4"] = Sweets.objects.filter(owner=request.user)


    # api = API('57fbffe56b594046b1a92aeaeabb3145')
    # query = request.GET.get('query')
    # results = api.search_recipes_complex(query=query)
    # context['parsed_results'] = json.loads(results)
    
    template = loader.get_template('uploadmenu.html')
    return HttpResponse(template.render(context, request)) 

#def my_form_view(request):
   # context = {}
    #context["dataset"] = Normal.objects.all()

    #return render(request, "uploadmenu.html", context)

def delete(request, id):
    normalone = Normal.objects.get(id=int(id))
    normalone.delete()
    return HttpResponseRedirect(reverse_lazy('myapp:my_form'))

def delete2(request, id):
    gravyone = Gravy.objects.get(id=int(id))
    gravyone.delete()
    return HttpResponseRedirect(reverse_lazy('myapp:my_form'))

def delete3(request, id):
    snacksone = Snacks.objects.get(id=int(id))
    snacksone.delete()
    return HttpResponseRedirect(reverse_lazy('myapp:my_form'))

def delete4(request, id):
    sweetsone = Sweets.objects.get(id=int(id))
    sweetsone.delete()
    return HttpResponseRedirect(reverse_lazy('myapp:my_form'))

def back_to_login(request):
    return HttpResponseRedirect(reverse_lazy('myapp:login'))



def menu(request):
    
    if request.method == 'POST':
        form = MenuItemForm(request.POST)
        if form.is_valid():
            all = form.save(commit=False)
            all.owner = request.user
            all.save()
            
            return redirect('myapp:menu')
    else:
        form = MenuItemForm()
    menu_item = MenuItem.objects.filter(owner=request.user)

    
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    meals = ['Breakfast', 'Lunch', 'Dinner']
    menu_chart = {}

    for day in days:
            menu_chart[day] = {}
            for meal in meals:
                menu_avialable = MenuItem.objects.filter(day=day[:3].lower(), meal=meal.lower(), owner=request.user)
                if menu_avialable:
                    menu_chart[day][meal] = menu_avialable[0].item
                else:
                    menu_chart[day][meal] = '-'


    context = {}
    context["dataset1"] = Normal.objects.filter(owner=request.user)
    context["dataset2"] = Gravy.objects.filter(owner=request.user)
    context["dataset3"] = Snacks.objects.filter(owner=request.user)
    context["dataset4"] = Sweets.objects.filter(owner=request.user)

    return render(request, 'menu.html', {'form': form, 'menu_item': menu_item, 'menu_chart': menu_chart, 'context':context})

#def NewChart(request, id):
    ls = MenuName.objects.get(owner=request.user, id=id)

    if request.method == "POST":
        if request.POST.get("newitem"):
           d = request.POST.get("newd")
           m = request.POST.get("newm")
           i = request.POST.get("newi")

           ls.item_set.create(day=d, meal=m, item=i)

    return render(request, "newchart.html", {"ls":ls})

def deletemenu(request, id):
    menuone = MenuItem.objects.get(id=int(id))
    menuone.delete()
    return HttpResponseRedirect(reverse_lazy('myapp:menu'))

def post_it(request):
    
    charts = ['chart1', 'chart2', 'chart3', 'chart4']
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    meals = ['Breakfast', 'Lunch', 'Dinner']
    for day in days:
        #menu_chart[day] = {}
        for meal in meals:
            menu_avialable = MenuItem.objects.filter(day=day[:3].lower(), meal=meal.lower(), owner=request.user)
            if menu_avialable:
                 postdata = Post(day=day, meal=meal, item=menu_avialable[0].item, owner=request.user)
                 postdata.save()
            else:
                postdata = Post(day=day, meal=meal, item="-", owner=request.user)
                postdata.save()


    menu_chart = {}
    for day in days:
        menu_chart[day] = {}
        for meal in meals:
            menu_items = Post.objects.filter(day=day[:3].lower(), meal=meal.lower(), owner=request.user)
            if menu_items:
                menu_chart[day][meal] = menu_items[0].item
            else:
                menu_chart[day][meal] = '-'

    post_data_list = Post.objects.filter(owner=request.user)
    print(post_data_list)
    return render(request, 'profile.html', {'menu_chart':menu_chart})


def automatic(request):
    menu_item = MenuItem.objects.filter(owner=request.user)
    days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
    meals = ['Breakfast', 'Lunch', 'Dinner']
    menu_chart = {}
    for day in days:
        menu_chart[day] = {}
        for meal in meals:
            menu_avialable_snacks = Snacks.objects.filter(owner=request.user)
            menu_avialable_garvy = Gravy.objects.filter(owner=request.user)
            menu_avialable_normal = Normal.objects.filter(owner=request.user)
            menu_avialable_sweets = Sweets.objects.filter(owner=request.user)
            i = 0
            if menu_avialable_snacks and meal=='Breakfast':
                
                menu_chart[day][meal] = menu_avialable_snacks[i].snacks
                i = i + 1
                
            elif menu_avialable_normal and meal=='Lunch':
                menu_chart[day][meal] = menu_avialable_normal[0].fullname
            

Signup_project/myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MEESY</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">

    <style>
*{
    
    font-family: 'Roboto', sans-serif;

}

.Meesy{
    font-style: italic;
    text-align: center;

}

chart table, th, td{
    border-style: solid;
    align-content: center;
    justify-content: center;
  
    border-collapse: collapse;
}



.TOPNAV a{
    float: left;
   display: block;
    color: #9B9B9B;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 1.2rem;
    text-transform: uppercase;
    padding-left: 20px;
}




.content{
    
    padding-top: 30px;
}
#badmos{
    color:white;
    background-color:white;
}
.logo{
    height:30px;
    width: 30px;
    position: relative;
    filter: invert(100%);
}
.logo>img{
    height: 155px;
    width: 220px;
    position: relative;
    top: -42px;
    left: 50px;
}
.navbar{
    display: flex;
    background: #444141;
    height: 114px;
    margin:-9px;
    position: fixed;
    width: 100%;
    top: 0;
    padding:4px;
    align-items:center;
}
#navitem{
    position: relative;
    left: 800px;
    color: white;
    height: 15px;
    
}
#navitem:hover{
    color:green;

}
*{
    font-family: 'Signika Negative', sans-serif;
    color: black;
}
td,th{
    border: 2px solid black ;
    border-radius: 10px;
}
.content{
   margin: 0px;
   height: 100vh;
    /* background-size: contain; */
}
.scroll-box {
  position: fixed;
  top: 112px;
  right: 0;
  width: 250px;
  height: 100%;
  background-color: #e49656;
  border: 1px solid ;
  overflow-y: scroll;
  padding: 10px;
}

.scroll-box h2 {
  margin-top: 0;
}

.scroll-box ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.scroll-box li {
  margin-bottom: 10px;
}

.scroll-box label {
  display: inline-block;
  width: 100px;
}

body{
    background-color: #e9a167;
    height: 100%;
}

.menuask{
	display:flex;
	flex-direction:column;
	justify-content:center;
	align-item:center;
}
.username{
    margin-left:200px;
    font-size:30px;
}
    </style>
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Signika+Negative&display=swap" rel="stylesheet">
</head>
<body>
    
    <div class="navbar">
    <div class = "logo"><h1 font-family: 'Roboto', sans-serif>MEAZY</h1></div>
    
    <div class="TOPNAV">
        
        <a href= "{% url 'myapp:profile' %}" class="PROFILE" id ="navitem">Home</a>
        <a href="{% url 'myapp:menu' %}" class="CREATECHART" id ="navitem">CREATE CHART</a>
        <a href="{% url 'myapp:my_form' %}" class="UPLOADDISHES" id ="navitem">UPLOAD DISHES</a>
        <a href="{% url 'myapp:back_to_login' %}" class="LOGOUT" id ="navitem">Logout</a>
    </div>
    </div>
    <br><br><br><br><br>
    
    <section class="content" name="content" id="content">
        {% block content %}

        {% endblock %}
    
</section>
</body>
</html>

Signup_project/myapp/templates/list.html
{% extends "base.html" %}
{% block content %}
<h1>{{ls.name}}</h1>
<form action="#" method="POST">
    {% csrf_token %}
<ul>
{% for items in ls.item_set.all %}
    {% if item.complete == True %}
        <li><input type="checkbox", value="clicked", name="c{{item.id}}" checked>{{items.text}}</li>
    {% else %}
        <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{items.text}}</li>
    {% endif %}
{% endfor %}
</ul>
<button type="submit", name="save", value="save">Save</button>
<input type="text", name="new">
<button type="submit", name="newItem", value="newItem">Add Item</button>
</form>
{% endblock %}

Signup_project/myapp/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>login Page</title>
  <!--<link rel="stylesheet" href="login css.css">-->
  <style>
  body{
    background:grey;
  }
  .menuask>h1{
	text-align:center;
	font-size:30px;
}
.menuask{
	margin-left:550px;
	border:2px solid black;
	width:400px;
	border-radius:20px;
	backdrop-filter:blur(8px);
  height: 400px
}
input[type="submit"]{
	border:2px solid black;
	border-radius:20px;
	text-align:center;
	display:block;
	margin:auto;
	width:100px;
	height:30px;
	background-color:#163932;
	color:white;
	transition:all 0.5s ease-in-out;
}
input[type="submit"]:hover{
	box-shadow: 0px 0px 20px 8px black;
	cursor:pointer;
}
button{
  
  text-align:center;
	display:block;
	margin:auto;
	width:100px;
	height:30px;
	background-color: white;
	color:black;
	transition:all 0.5s ease-in-out;

}
button>a{
text-decoration: none;
}
form{
  text-align: center;
}


  </style>
</head>

<body>
<div class="alert-box">
  <p class="alert">msg</p>
</div>

  <!--
  <div class="form">
    <h1 class="heading">login</h1>
    <input type="email" placeholder="Email" autocomplete="off" class="email" required>
    <input type="password" placeholder="Password" autocomplete="off" class="password" required>
    <button class="submit">Log In</button>
    <a href="signup.html" class="link">don't have an account? Register one</a>
  </div>
  -->
<div class="menuask">
  <h1>LOGIN</h1>
  <br><br><br><br>
  <form method="POST" >
    {% csrf_token %}
    <input type="text" name="username" placeholder="username"><br>
    <input type="password" name="password" placeholder="password"><br>
    <br><br><br>
    <input type="submit" value="submit">
    
  </form>
  <br>
  <button><a href="signup/">Sign Up</a></button>
  </div>
</body>
</html>

Signup_project/myapp/templates/menu.html
<style>

.menuask>h1{
	text-align:center;
	font-size:30px;
}
.menuask{
	margin-left:550px;
	border:2px solid black;
	width:300px;
	border-radius:20px;
	backdrop-filter:blur(8px);
}
button[type="submit"]{
	border:2px solid black;
	border-radius:20px;
	text-align:center;
	display:block;
	margin:auto;
	width:100px;
	height:30px;
	background-color:#163932;
	color:white;
	transition:all 0.5s ease-in-out;
}
button[type="submit"]:hover{
	box-shadow: 0px 0px 20px 8px black;
	cursor:pointer;
}
ul{
	list-style:circle;
}
.mainbox{
	margin-left:200px;
}
.menuchart{
	margin-left:630px;
	font-size:30px;
	padding-top:20px;
}
.mainbox2{
	padding:10px;
	margin-left:600px;
}
</style>

{% extends 'base.html' %}

{% block content%}
<section class ="menuask">
	<h1>Menu</h1>
	<h2> {{ls.name}} </h2>
	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Save</button>
	</form>
	</section>
	<h1 class="menuchart">Menu Chart</h1>
	
	<table class="mainbox" style="width: 60%; height: 400px; text-align: center;">
		<thead>
			<tr>
				<th>Day</th>
				<th>Breakfast</th>
				<th>Lunch</th>
				<th>Dinner</th>
			</tr>
		</thead>
		<tbody>
			{% for day, meals in menu_chart.items %}
				<tr>
					<td>{{ day }}</td>
					{% for meal, item in meals.items %}
						<td>{{ item }} <br> </td>
					{% endfor %}
				</tr>
			{% endfor %}
		</tbody>
	</table>

	

	<h2 class="menuchart">Current Menu</h2>
	{% if menu_item %}
		<table class="mainbox2">
			<thead>
				<tr>
					<th>Day</th>
					<th>Meal</th>
					<th>Item</th>
				</tr>
			</thead>
			<tbody>
				{% for item in menu_item %}
					<tr>
						<td>{{ item.day }}</td>
						<td>{{ item.meal }}</td>
						<td>{{ item.item }}</td>
						<td><a href="deletemenu/{{ item.id }}">delete</a></td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	{% else %}
		<p>No items in the menu yet.</p>
	{% endif %}


	<div class="scroll-box">
  
	<h3 ><u>NORMAL-VEGGIES</u></h3>
	<ul>
    <div class="lass">
        {% for item in context.dataset1 %}
            <li style="color: #163923"> {{item.fullname}} </li>
        {% endfor %}
    </div>
    </ul>
	<hr>
	<h3><u>GRAVY-SABJI</u></h3>
	<ul>
    <div class="lass">
        {% for item in context.dataset2 %}
            <li style="color: #163923"> {{item.gravy}} </li>
        {% endfor %}
    </div>
    </ul>
	<hr>
	<h3><u>SNACKS</u></h3>
	<ul>
    <div class="lass">
        {% for item in context.dataset3 %}
            <li style="color: #163923"> {{item.snacks}} </li>
        {% endfor %}
    </div>
    </ul>
	<hr>
	<h3><u>SWEETS</u></h3>
	<ul>
    <div class="lass">
        {% for item in context.dataset4 %}
            <li style="color: #163923"> {{item.sweets}} </li>
        {% endfor %}
    </div>
    </ul>
	
</div>
{% endblock %}
</html>

Signup_project/myapp/templates/newchart.html
{% extends "base.html" }

{% block content %}
<h1> {{ls.name_of_chart}} </h1>

<form method="POST", action"#">
{% csrf_token %}
    <input type="text" name="">
    <ul>
    {% for item in ls.item_set.all %}
    <li> {{item.d}} </li>

    {% endfor %}
    <ul>
</form>